image: "python"

before_script:
  - pip install --proxy http://43.196.177.37:8881 -r requirements.txt
  - pip install --proxy http://43.196.177.37:8881 --no-deps nnabla
  - pip install --proxy http://43.196.177.37:8881 --no-deps nnabla_ext_cuda101

stages:
  - Analyze
  - Test

flake8:
  stage: Analyze
  allow_failure: True
  script:
    - flake8 . --max-line-length=120

unit_test:
  stage: Test
  script:
    - pytest -v
