image: "python"

before_script:
  - pip install --proxy http://43.196.177.37:8881 -r requirements.txt
  - pip install --proxy http://43.196.177.37:8881 --no-deps nnabla

stages:
  - Analyze
  - Test

flake8:
  stage: Analyze
  allow_failure: true
  script:
    - flake8 . --max-line-length=120

pylint:
  stage: Analyze
  allow_failure: true
  script:
    - pylint .

unit_test:
  stage: Test
  script:
    - pytest -v
