name: Build nnabla-nas
on: [push]

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build PDF
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
        build-command: "make latexpdf"    

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: nnabla-nas-pdf
        path: ./docs/build/latex/nnablanas.pdf
  
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Instal dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with pyflakes
      run: |
        flake8 . --max-line-length=120

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Instal dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Unit test
      run: |
        pytest --cov=nnabla_nas tests/
